baseurl = "https://yutani.rbind.io/"
languageCode = "en"
title = "Hiroaki Yutani's Blog"
theme = "hucore"
disqusShortname = "yutani"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
description = "Rstats-fu wannabe in the Far East"
keywords = ["rstats", "R"]
author = "Hiroaki Yutani"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["r"]

[[params.social]]
url = "https://github.com/yutannihilation"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/yutannihilation"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[outputs]
home = [ "HTML", "AMP", "RSS"]
page = [ "HTML", "AMP", "RSS"]
