baseurl = "https://test-yutani.rbind.io/"
languageCode = "en"
title = "Hiroaki Yutani"
theme = "hemingway2"
disqusShortname = "yutani"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[params]

[params.highlight]
style = "github"
languages = ["r"]

[[params.social]]
url = "https://github.com/yutannihilation"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/yutannihilation"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
